baseURL = 'https://annamakarrenko.github.io/practice-2025/'
publishDir = '..public'
languageCode = 'ru-ru'
theme = 'ananke'

[outputs]
home = ['HTML', 'RSS']

[menu]
[[menu.main]]
name = "Главная"
url = "/"
weight = 1

[[menu.main]]
name = "О проекте"
url = "/about/"
weight = 2

[[menu.main]]
name = "Участники"
url = "/participants/"
weight = 3

[[menu.main]]
name = "Журнал"
url = "/journal/"
weight = 4

[[menu.main]]
name = "Ресурсы"
url = "/resources/"
weight = 5

[module]
[[module.mounts]]
source = "static"
target = "static"