name: Deploy Hugo

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.146.4'
          extended: true

      - name: Build info
        run: |
          echo "### Hugo version ###"
          hugo version
          echo "### Project structure ###"
          ls -la
          echo "### Themes ###"
          ls -la themes/

      - name: Build site
        run: |
          hugo --minify --gc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public